(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.BalloonGas=api;}(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
// Calculation specification: gas_calc_2026.py.
var MODELS={
1000:{massG:1000,k:132/23.6,lengthM:1.8,diameterM:1.15,burstM:8.2},
1200:{massG:1200,k:null,lengthM:2.0,diameterM:1.27,burstM:8.9},
1500:{massG:1500,k:138/23.6,lengthM:2.2,diameterM:1.4,burstM:10.0},
2000:{massG:2000,k:148/23.6,lengthM:2.5,diameterM:1.6,burstM:11.3},
3000:{massG:3000,k:158/23.6,lengthM:2.95,diameterM:1.9,burstM:13.5}};
var PARACHUTES={4.28:430,7.28:230,10.4:140};
var DENSITY=1.1138,GAMMA=1.67;
var DEFAULTS={inputMode:'normal',balloonMassG:1500,componentMassG:1000,otherMassG:0,terminalVelocityMps:4.28,verificationOtherMassG:1835,targetAscentRate:5,temperatureC:26,cylinderTemperatureC:25,pressureHpa:1010,targetCylinderPressureMpa:0.2,firstCylinderOffsetMpa:0,polytropicN:1.3,cylinderProcess:'polytropic',cylinders:[1,2,3,4].map(function(id){return{id:String(id),volumeL:47,pressureMpa:14};})};
function finite(v,label,min,max){v=Number(v);if(!Number.isFinite(v)||(min!=null&&v<min)||(max!=null&&v>max))throw new RangeError(label+'が不正です');return v;}
function round(v,d){var s=Math.pow(10,d==null?2:d);return Math.round((v+Number.EPSILON)*s)/s;}
function opts(raw){var o=Object.assign({},DEFAULTS,raw||{});o.cylinders=(raw&&raw.cylinders?raw.cylinders:DEFAULTS.cylinders).map(function(c){return Object.assign({},c);});return o;}
function modelFor(mass){var key=String(Math.round(finite(mass,'気球質量',1))),m=MODELS[key];if(!m)throw new RangeError('対応していない気球質量です: '+key+' g');if(!Number.isFinite(m.k))throw new RangeError(key+' gの上昇速度係数は未確定のため使用できません');return m;}
function parachuteMass(v){v=finite(v,'終端速度',0.01);var key=Object.keys(PARACHUTES).find(function(x){return Math.abs(Number(x)-v)<1e-9;});if(key==null)throw new RangeError('対応していない終端速度です: '+v+' m/s');return PARACHUTES[key]+405;}
// gas_calc_2026.py: calc_buoyancy
function solvePureLiftKg(weight,rate,k){weight=finite(weight,'総重量',0.001);rate=finite(rate,'目標上昇速度',0.01);k=finite(k,'上昇速度係数',0.01);var lift=10,iterations=0,ok=false;function f(x){return Math.pow(rate,6)*Math.pow(weight+x,2)-Math.pow(k,6)*Math.pow(x,3);}function df(x){return 2*Math.pow(rate,6)*(weight+x)-3*Math.pow(k,6)*Math.pow(x,2);}for(var i=0;i<30;i+=1){var y=f(lift);iterations=i+1;if(Math.abs(y)<=1e-4){ok=true;break;}var slope=df(lift);if(!Number.isFinite(slope)||Math.abs(slope)<1e-12)break;lift-=y/slope;if(!Number.isFinite(lift)||lift<=0)break;}if(!ok)throw new RangeError('純浮力を30回以内に収束できません');return{liftKg:lift,converged:true,iterations:iterations};}
function calculateGasVolumeL(lift,temp,pressure){lift=finite(lift,'全浮力',0);temp=finite(temp,'充填時温度')+273.15;pressure=finite(pressure,'充填時大気圧',0.01);return(lift/DENSITY)*temp*1013.25/(273.15*pressure)*1000;}
function cylinders(raw){if(!Array.isArray(raw)||raw.length!==4)throw new RangeError('ボンベは4本分を入力してください');return raw.map(function(c,i){return{id:c.id||String(i+1),volumeL:finite(c.volumeL,(i+1)+'本目の容積',0.01),pressureMpa:finite(c.pressureMpa,(i+1)+'本目の初期圧力',0,15)};});}
// gas_calc_2026.py: _fillable_volume_polytropic
function capacity(c,i,o,n){var atm=finite(o.pressureHpa,'充填時大気圧',0.01)*1e-4,end=finite(o.targetCylinderPressureMpa,'終了目標残圧',0),offset=i===0?finite(o.firstCylinderOffsetMpa,'1本目オフセット',0):0,T=finite(o.cylinderTemperatureC,'残圧測定時温度')+273.15;n=finite(n,'ポリトロープ指数',1,GAMMA);if(end-offset<=0)throw new RangeError('終了目標残圧は1本目オフセットより大きくしてください');if(c.pressureMpa<=end)return 0;var T2=T*Math.pow((end-offset)/c.pressureMpa,(n-1)/n);return Math.max(0,c.volumeL*((c.pressureMpa-offset)/atm)-c.volumeL*(end/atm)*(T/T2));}
// gas_calc_2026.py: _solve_residual_polytropic
function residual(C,n){var exponent=(n-1)/n;function g(x){return C*Math.pow(x,exponent)-x;}function digit(base,step,count){var prev=0;for(var i=0;i<=count;i+=1){if(g(base+i*step)<0)return i-1;prev=i;}return prev;}var d0=digit(0,1,15),base=d0,d1=digit(base,.1,10);base+=d1*.1;var d2=digit(base,.01,10);base+=d2*.01;var d3=digit(base,.001,10);return round(d0+d1*.1+d2*.01+d3*.001,2);}
// gas_calc_2026.py: calc_gas
function planFor(required,raw,n,label,key){var o=opts(raw),cs=cylinders(o.cylinders);required=finite(required,'必要ガス量',0);n=finite(n,'ポリトロープ指数',1,GAMMA);var caps=cs.map(function(c,i){return capacity(c,i,o,n);}),remaining=required;var rows=cs.map(function(c,i){var used=remaining<=0?0:(remaining-caps[i]>0?caps[i]:remaining);remaining=Math.max(0,remaining-used);var status=caps[i]<=1e-9?'unused':(Math.abs(used-caps[i])<1e-9?'full':(used===0?'unused':'partial'));return{id:c.id,initialPressureMpa:c.pressureMpa,volumeL:c.volumeL,capacityL:caps[i],usedL:used,status:status,residualPressureMpa:null};});var pi=rows.findIndex(function(r){return r.status==='partial';});if(pi>=0){var c=cs[pi],atm=o.pressureHpa*1e-4,V4=c.volumeL*(c.pressureMpa/atm),V3=V4-rows[pi].usedL,C=(V3/c.volumeL)*atm*Math.pow(Math.abs(c.pressureMpa),(1-n)/n);rows[pi].residualPressureMpa=residual(C,n);}rows.forEach(function(r){if(r.status==='full')r.residualPressureMpa=o.targetCylinderPressureMpa;});var full=rows.filter(function(r){return r.status==='full';}).length,equiv=full===4?NaN:(pi>=0?full+rows[pi].usedL/rows[pi].capacityL:full);return{key:key,model:label,exponentN:n,requiredGasL:required,availableGasL:caps.reduce(function(a,b){return a+b;},0),remainingGasL:remaining,insufficient:remaining>1e-6||!Number.isFinite(equiv),physicalCylindersUsed:rows.filter(function(r){return r.status!=='unused';}).length,workbookEquivalentCount:equiv,cylinders:rows};}
function allPlans(required,raw){var o=opts(raw);return{quasiStatic:planFor(required,o,1,'準静的','quasiStatic'),polytropic:planFor(required,o,o.polytropicN,'ポリトロープ (n='+Number(o.polytropicN)+')','polytropic'),adiabatic:planFor(required,o,GAMMA,'断熱','adiabatic')};}
function calculateCylinderPlan(required,raw){var o=opts(raw),p=allPlans(required,o);return o.cylinderProcess==='adiabatic'?p.adiabatic:(o.cylinderProcess==='quasi-static'?p.quasiStatic:p.polytropic);}
function pressureAt(alt){alt=finite(alt,'高度',0,40);var p20=226.321*Math.exp((-9.80665*.0289644*9000)/(8.31432*216.65)),p32=p20*Math.pow((216.65+.001*12000)/216.65,-34.1632);if(alt===0)return Math.pow((44.331514-alt)/11.880516,5.255877);if(alt>32)return p32*Math.pow((227.65+.0028*(alt*1000-32000))/227.65,-12.23);if(alt>20)return p20*Math.pow((216.65+.001*(alt*1000-20000))/216.65,-34.1632);return 226.321*Math.exp((-9.80665*.0289644*(alt*1000-11000))/(8.31432*216.65));}
function temperatureAt(alt,ground){alt=finite(alt,'高度',0,40);var t20=216.66,t32=t20+12;if(alt===0)return finite(ground,'地表温度')+273.16;if(alt>32)return t32+.0028*(alt*1000-32000);if(alt>20)return t20+.001*(alt*1000-20000);return t20;}
function altitudes(){return Array.from({length:401},function(_,i){return 40-.05*i;}).concat([19,18,17,16,15,13.5,12.7,12,0]);}
// gas_calc_2026.py: calc_burst_altitude
function burst(gasL,m,raw){var o=opts(raw),ground=finite(o.cylinderTemperatureC,'残圧測定時温度'),std=Math.PI*m.lengthM*Math.pow(m.diameterM,2)/6*1000,fill=finite(gasL,'充填体積',.001)/std,area=Math.pow(fill*fill,1/3),length=m.lengthM*Math.pow(fill,1/3),diameter=m.diameterM*Math.pow(fill,1/3),sphere=2*Math.pow((3*std)/(4*Math.PI),1/3)/10*Math.pow(fill,1/3),surfaceT=ground+273.16,surfaceP=pressureAt(0),alts=altitudes(),h={ellipsoidThickness:[],ellipsoidLength:[],ellipsoidDiameter:[],sphereDiameter:[]};alts.forEach(function(alt){var expansion=temperatureAt(alt,ground)/surfaceT*surfaceP/pressureAt(alt),scale=Math.pow(expansion,1/3);h.ellipsoidThickness.push(130/Math.pow(expansion*expansion,1/3)/area<5);h.ellipsoidLength.push(length*scale>=m.burstM);h.ellipsoidDiameter.push(diameter*scale>=m.burstM);h.sphereDiameter.push(sphere*scale>=m.burstM);});function firstFalse(values){for(var i=0;i<values.length;i+=1)if(!values[i])return round(alts[i],2);return alts[alts.length-1];}var methods={ellipsoidThickness:firstFalse(h.ellipsoidThickness),ellipsoidLength:firstFalse(h.ellipsoidLength),ellipsoidDiameter:firstFalse(h.ellipsoidDiameter),sphereDiameter:firstFalse(h.sphereDiameter)};return{defaultKm:methods.sphereDiameter,defaultMethod:'sphereDiameter',methods:methods,fillGeometry:{ellipsoidLengthM:length,ellipsoidDiameterM:diameter,equivalentDiameterM:sphere}};}
function calculate(raw){var o=opts(raw),m=modelFor(o.balloonMassG),recovery=o.inputMode==='verification'?0:parachuteMass(o.terminalVelocityMps),other=o.inputMode==='verification'?finite(o.verificationOtherMassG,'気球以外の総重量',0):finite(o.componentMassG,'コンポーネント重量',0)+finite(o.otherMassG,'その他重量',0)+recovery,total=(finite(o.balloonMassG,'気球質量',0)+other)/1000,lift=solvePureLiftKg(total,o.targetAscentRate,m.k),Q=total+lift.liftKg,V=calculateGasVolumeL(Q,o.temperatureC,o.pressureHpa),plans=allPlans(V,o),selected=o.cylinderProcess==='adiabatic'?plans.adiabatic:(o.cylinderProcess==='quasi-static'?plans.quasiStatic:plans.polytropic);return{inputs:o,model:m,recoveryMassG:recovery,totalMassKg:total,pureLiftKg:lift.liftKg,buoyancyConverged:lift.converged,buoyancyIterations:lift.iterations,totalLiftKg:Q,gasVolumeL:V,gasVolumeM3:V/1000,gasModels:plans,cylinders:selected,burst:burst(V,m,o)};}
return{BALLOON_MODELS:MODELS,PARACHUTE_TABLE:PARACHUTES,DEFAULTS:DEFAULTS,DENSITY_DIFFERENCE_KG_M3:DENSITY,HELIUM_GAMMA:GAMMA,parachuteMassG:parachuteMass,solvePureLiftKg:solvePureLiftKg,calculateGasVolumeL:calculateGasVolumeL,calculateCylinderPlan:calculateCylinderPlan,calculateAllCylinderModels:allPlans,calculateBurstAltitudes:burst,atmosphereAtKm:function(alt,ground){return{pressureHpa:pressureAt(alt),temperatureK:temperatureAt(alt,ground==null?25:ground)};},calculate:calculate,round:round};
}));
