/* Generated by scripts/build-service-worker.mjs. */
'use strict';

var CACHE_PREFIX = 'wasa-predictor-';
var CACHE_VERSION = '3a5f33cf0bdf';
var APP_CACHE_NAME = CACHE_PREFIX + 'app-' + CACHE_VERSION;
// v2 stores CORS-readable responses. v1 may contain opaque responses created
// before image export required cross-origin map pixels.
var TILE_CACHE_NAME = CACHE_PREFIX + 'tiles-v2-cors';
var TILE_CACHE_LIMIT = 500;
var APP_SHELL = [
    "./",
    "./css/context-help.css",
    "./css/gas-calculator.css",
    "./css/images/layers-2x.png",
    "./css/images/layers.png",
    "./css/images/marker-icon-2x.png",
    "./css/images/marker-icon.png",
    "./css/images/marker-shadow.png",
    "./css/images/ui-icons_444444_256x240.png",
    "./css/images/ui-icons_555555_256x240.png",
    "./css/images/ui-icons_777620_256x240.png",
    "./css/images/ui-icons_777777_256x240.png",
    "./css/images/ui-icons_cc0000_256x240.png",
    "./css/images/ui-icons_ffffff_256x240.png",
    "./css/jquery-ui.css",
    "./css/leaflet.css",
    "./css/predictor-mobile.css",
    "./css/predictor.css",
    "./css/uncertainty.css",
    "./data/inland_water_japan_w09_05.geojson",
    "./data/land-sea-datasets.json",
    "./data/land_japan_raw.geojson",
    "./favicon.ico",
    "./images/app-icon-192.png",
    "./images/app-icon-512.png",
    "./images/arrow.png",
    "./images/balloon-sm.png",
    "./images/balloon.png",
    "./images/csv.gif",
    "./images/drag_handle.png",
    "./images/kml.png",
    "./images/marker-sm-black.png",
    "./images/marker-sm-red.png",
    "./images/pop-marker.png",
    "./images/target-1-sm.png",
    "./images/target-1.png",
    "./images/target-10.png",
    "./images/target-11.png",
    "./images/target-12.png",
    "./images/target-13.png",
    "./images/target-14.png",
    "./images/target-15.png",
    "./images/target-16.png",
    "./images/target-17.png",
    "./images/target-18.png",
    "./images/target-2.png",
    "./images/target-3.png",
    "./images/target-4.png",
    "./images/target-5.png",
    "./images/target-6.png",
    "./images/target-7.png",
    "./images/target-8-sm.png",
    "./images/target-8.png",
    "./images/target-9.png",
    "./images/target-blue.png",
    "./images/target-red.png",
    "./images/target-yellow.png",
    "./images/tipsy.gif",
    "./index.html",
    "./js/calc/balloon-gas.js",
    "./js/calc/gas-calculator-template.js",
    "./js/calc/gas-calculator-ui.js",
    "./js/chart.min.js",
    "./js/colour-map.js",
    "./js/core/app-errors.js",
    "./js/core/app-notifications.js",
    "./js/core/app-shell.js",
    "./js/core/app-storage.js",
    "./js/core/context-help.js",
    "./js/core/export-service.js",
    "./js/core/history-controller.js",
    "./js/core/map-display-controller.js",
    "./js/core/map-layer-registry.js",
    "./js/core/results-workspace.js",
    "./js/core/run-repository.js",
    "./js/core/settings-repository.js",
    "./js/domain/run-record.js",
    "./js/geo/land-sea-classifier.js",
    "./js/html2canvas.min.js",
    "./js/jquery-3.3.1.min.js",
    "./js/jquery-ui.min.js",
    "./js/jquery.jookie.js",
    "./js/jquery.tipsy.js",
    "./js/leaflet.js",
    "./js/moment.js",
    "./js/pred/auto-search-core.js",
    "./js/pred/auto-search.js",
    "./js/pred/ehime-controller.js",
    "./js/pred/ehime-enhancements.js",
    "./js/pred/hourly-controller.js",
    "./js/pred/landsea.js",
    "./js/pred/launch-window.js",
    "./js/pred/log-overlay.js",
    "./js/pred/mobile-ui.js",
    "./js/pred/pred-api-client.js",
    "./js/pred/pred-chart-core.js",
    "./js/pred/pred-chart.js",
    "./js/pred/pred-collaborate.js",
    "./js/pred/pred-common.js",
    "./js/pred/pred-config.js",
    "./js/pred/pred-cookie.js",
    "./js/pred/pred-event.js",
    "./js/pred/pred-job-store.js",
    "./js/pred/pred-map.js",
    "./js/pred/pred-new.js",
    "./js/pred/pred-ui.js",
    "./js/pred/pred.js",
    "./js/pred/prediction-renderer.js",
    "./js/pred/prediction-results-ui.js",
    "./js/pred/prediction-runner.js",
    "./js/pred/request-context.js",
    "./js/pred/uncertainty-analysis.js",
    "./js/pred/uncertainty-core.js",
    "./js/pred/uncertainty-template.js",
    "./js/pred/variant-profile-registry.js",
    "./js/pred/workload-core.js",
    "./manifest.json",
    "./ports.json",
    "./sites.json"
];

function isApiRequest(url) {
    return url.hostname === 'api.v2.sondehub.org' ||
        url.hostname === 'api.open-meteo.com' ||
        url.pathname.startsWith('/api/') ||
        url.pathname === '/__server-info';
}

function isMapTile(url) {
    return url.hostname.endsWith('tile.openstreetmap.org') ||
        url.hostname.endsWith('tile.opentopomap.org') ||
        url.hostname.endsWith('arcgisonline.com') ||
        url.hostname.endsWith('basemaps.cartocdn.com');
}

async function trimCache(cache, maximumEntries) {
    var keys = await cache.keys();
    while (keys.length > maximumEntries) {
        await cache.delete(keys.shift());
    }
}

async function cacheFirstTile(request) {
    var cache = await caches.open(TILE_CACHE_NAME);
    var cached = await cache.match(request);
    if (cached && !(request.mode === 'cors' && cached.type === 'opaque')) return cached;
    if (cached) await cache.delete(request);
    var response = await fetch(request);
    var corsCompatible = request.mode !== 'cors' || response.type !== 'opaque';
    if (response && corsCompatible && (response.ok || response.type === 'opaque')) {
        await cache.put(request, response.clone());
        await trimCache(cache, TILE_CACHE_LIMIT);
    }
    return response;
}

async function cacheFirstAppShell(request) {
    var cache = await caches.open(APP_CACHE_NAME);
    var cached = await cache.match(request);
    if (!cached && (request.mode === 'navigate' || new URL(request.url).pathname.endsWith('.html'))) {
        cached = await cache.match('./index.html');
    }
    if (cached) return cached;
    return fetch(request);
}

self.addEventListener('install', function (event) {
    event.waitUntil(caches.open(APP_CACHE_NAME).then(function (cache) {
        return cache.addAll(APP_SHELL);
    }));
});

self.addEventListener('activate', function (event) {
    event.waitUntil(caches.keys().then(function (cacheNames) {
        return Promise.all(cacheNames.filter(function (cacheName) {
            return cacheName.startsWith(CACHE_PREFIX) && cacheName !== APP_CACHE_NAME && cacheName !== TILE_CACHE_NAME;
        }).map(function (cacheName) {
            return caches.delete(cacheName);
        }));
    }).then(function () {
        return self.clients.claim();
    }));
});

self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', function (event) {
    if (event.request.method !== 'GET') return;
    var requestUrl = new URL(event.request.url);
    if (isApiRequest(requestUrl)) return;
    if (event.request.mode === 'navigate' || requestUrl.pathname.endsWith('.html')) {
        event.respondWith(cacheFirstAppShell(event.request));
        return;
    }
    if (isMapTile(requestUrl)) {
        event.respondWith(cacheFirstTile(event.request));
        return;
    }
    if (requestUrl.origin === self.location.origin) {
        // APP_CACHE_NAME is content-versioned and pre-cached as one unit.
        // Never revalidate individual files into an older cache: doing so can
        // combine a new index with old modules until a hard refresh.
        event.respondWith(cacheFirstAppShell(event.request));
    }
});
